name: .NET 8.0 Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug]

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    - name: Find .csproj file
      shell: pwsh
      run: |
        echo "Searching for .csproj file..."
        csproj_file=$(find . -name "*.csproj" -print -quit)
        echo "Found .csproj file: $csproj_file"
        echo "csproj_file=$csproj_file" >> $GITHUB_ENV

    - name: Restore the application
      run: msbuild $csproj_file /t:Restore /p:Configuration=$env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}
        
    - name: Publish application
      shell: cmd
      run: dotnet publish -p:PublishSingleFile=true --self-contained false -o %cd%\publish\

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ZIP Build
        path: .\publish\
